#
# This file will be included by cmake/share/Files.cmake
#
# cmake/reflect/_Libraries.cmake is generated by
# `mulle-sourcetree-to-cmake` via `mulle-sde reflect`.
# Edits will be lost.
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 2A45651D-64C7-4417-A29B-D7AED105CFC4;AppleFoundation;no-all-load,no-build,no-cmake-inherit,no-delete,no-dependency,no-fs,no-share,no-update,only-framework,only-platform-darwin;Foundation
# Disable with : `mulle-sourcetree mark AppleFoundation `
# Disable for this platform: `mulle-sourcetree mark AppleFoundation no-cmake-platform-linux`
#
if( ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
   if( NOT FOUNDATION_FRAMEWORK)
      find_library( FOUNDATION_FRAMEWORK NAMES Foundation)
      message( STATUS "FOUNDATION_FRAMEWORK is ${FOUNDATION_FRAMEWORK}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( FOUNDATION_FRAMEWORK)
         #
         # Add FOUNDATION_FRAMEWORK to OS_SPECIFIC_FRAMEWORKS list.
         # Disable with: `mulle-sourcetree mark AppleFoundation no-cmake-add`
         #
         set( OS_SPECIFIC_FRAMEWORKS
            ${OS_SPECIFIC_FRAMEWORKS}
            ${FOUNDATION_FRAMEWORK}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         # Disable with: `mulle-sourcetree mark AppleFoundation no-require-link`
         message( FATAL_ERROR "FOUNDATION_FRAMEWORK was not found")
      endif()
   endif()
endif()
