# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 2A45651D-64C7-4417-A29B-D7AED105CFC4;AppleFoundation;no-all-load,no-build,no-cmake-inherit,no-delete,no-dependency,no-fs,no-share,no-update,only-framework,only-platform-darwin;Foundation
# Disable with : `mulle-sourcetree mark AppleFoundation `
# Disable for this platform: `mulle-sourcetree mark AppleFoundation no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark AppleFoundation no-cmake-sdk-<name>`
#
if( ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
   if( COLLECT_OS_SPECIFIC_FRAMEWORKS_AS_NAMES)
      list( APPEND OS_SPECIFIC_FRAMEWORKS "Foundation")
   else()
      if( NOT APPLE_FOUNDATION_FRAMEWORK)
         find_library( APPLE_FOUNDATION_FRAMEWORK NAMES
            Foundation
         )
         message( STATUS "APPLE_FOUNDATION_FRAMEWORK is ${APPLE_FOUNDATION_FRAMEWORK}")
         #
         # The order looks ascending, but due to the way this file is read
         # it ends up being descending, which is what we need.
         #
         if( APPLE_FOUNDATION_FRAMEWORK)
            #
            # Add APPLE_FOUNDATION_FRAMEWORK to OS_SPECIFIC_FRAMEWORKS list.
            # Disable with: `mulle-sourcetree mark AppleFoundation no-cmake-add`
            #
            list( APPEND OS_SPECIFIC_FRAMEWORKS ${APPLE_FOUNDATION_FRAMEWORK})
            # intentionally left blank
         else()
            # Disable with: `mulle-sourcetree mark AppleFoundation no-require-link`
            message( SEND_ERROR "APPLE_FOUNDATION_FRAMEWORK was not found")
         endif()
      endif()
   endif()
endif()
