# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 2A45651D-64C7-4417-A29B-D7AED105CFC4;AppleFoundation;no-all-load,no-build,no-cmake-inherit,no-delete,no-dependency,no-fs,no-share,no-update,only-framework,only-platform-darwin;Foundation
# Disable with : `mulle-sourcetree mark AppleFoundation `
# Disable for this platform: `mulle-sourcetree mark AppleFoundation no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark AppleFoundation no-cmake-sdk-<name>`
#
if( ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
   if( COLLECT_OS_SPECIFIC_FRAMEWORKS_AS_NAMES)
      list( APPEND OS_SPECIFIC_FRAMEWORKS "Foundation")
   else()
      if( NOT APPLE_FOUNDATION_FRAMEWORK)
         foreach( _TMP_APPLE_FOUNDATION_FRAMEWORK_TARGET Foundation)
            if( TARGET ${_TMP_APPLE_FOUNDATION_FRAMEWORK_TARGET})
               set( APPLE_FOUNDATION_FRAMEWORK ${_TMP_APPLE_FOUNDATION_FRAMEWORK_TARGET})
               break()
            endif()
         endforeach()
         if( NOT APPLE_FOUNDATION_FRAMEWORK)
            find_library( APPLE_FOUNDATION_FRAMEWORK NAMES
               Foundation
            )
         endif()
         message( STATUS "APPLE_FOUNDATION_FRAMEWORK is ${APPLE_FOUNDATION_FRAMEWORK}")
      endif()
      if( APPLE_FOUNDATION_FRAMEWORK)
            #
            # Add APPLE_FOUNDATION_FRAMEWORK to OS_SPECIFIC_FRAMEWORKS list.
            # Disable with: `mulle-sourcetree mark AppleFoundation no-cmake-add`
            #
            if( NOT ${APPLE_FOUNDATION_FRAMEWORK} IN_LIST OS_SPECIFIC_FRAMEWORKS)
               list( APPEND OS_SPECIFIC_FRAMEWORKS ${APPLE_FOUNDATION_FRAMEWORK})
            endif()
            # intentionally left blank
      else()
         # Disable with: `mulle-sourcetree mark AppleFoundation no-require-link`
         message( SEND_ERROR "APPLE_FOUNDATION_FRAMEWORK was not found in Foundation")
      endif()
   endif()
endif()
